import { useState } from 'react'

function PageHeader({ title, sub, noMargin }) {
  return (
    <div style={{marginBottom:noMargin?0:24}}>
      <h1 style={{fontSize:22,fontWeight:800,color:'var(--text)',margin:'0 0 4px',letterSpacing:'-0.02em'}}>{title}</h1>
      {sub&&<p style={{fontSize:13,color:'var(--text3)',margin:0}}>{sub}</p>}
    </div>
  )
}

function InfoItem({ label, val }) {
  return (
    <div style={{background:'rgba(255,255,255,0.03)',borderRadius:7,padding:'8px 10px'}}>
      <div style={{fontSize:10,color:'var(--text3)',textTransform:'uppercase',letterSpacing:'.06em',marginBottom:2}}>{label}</div>
      <div style={{fontSize:13,fontWeight:600,color:'var(--text)'}}>{val}</div>
    </div>
  )
}

function WebsiteStrengthBar({ signal }) {
  const map = {'No website':{pct:5,color:'#ef4444'},'Social only':{pct:25,color:'#f97316'},'Basic builder':{pct:50,color:'#f59e0b'},'Has website':{pct:80,color:'#6d8a40'}}
  const {pct,color} = map[signal]||{pct:50,color:'#6b7280'}
  return (
    <div style={{width:'100%'}}>
      <div style={{display:'flex',justifyContent:'space-between',fontSize:10,color:'var(--text3)',marginBottom:3}}>
        <span>Website strength</span><span style={{color}}>{signal}</span>
      </div>
      <div style={{height:4,background:'rgba(255,255,255,0.07)',borderRadius:2}}>
        <div style={{height:'100%',width:`${pct}%`,background:color,borderRadius:2,transition:'width 0.6s'}}/>
      </div>
    </div>
  )
}

function ScoreBar({ score }) {
  const color = score>=75?'#ef4444':score>=50?'#f97316':'#6b7280'
  return (
    <div style={{height:5,background:'rgba(255,255,255,0.07)',borderRadius:3}}>
      <div style={{height:'100%',width:`${score}%`,background:color,borderRadius:3,transition:'width 0.6s'}}/>
    </div>
  )
}

export { PageHeader, InfoItem, WebsiteStrengthBar, ScoreBar }

export const AU_STATES = [
  { label: 'South Australia', short: 'SA', suburbs: ['Adelaide CBD','Glenelg','Norwood','Unley','Prospect','Marion','Salisbury','Port Adelaide','Morphett Vale','Mount Barker','Victor Harbor','Murray Bridge','Whyalla','Mount Gambier','Port Augusta','Port Pirie','Gawler','Elizabeth','Modbury','Tea Tree Gully','Golden Grove','Mawson Lakes','Munno Para','Christies Beach','Noarlunga','Aldinga Beach','Hallett Cove','Westfield Marion','Burnside','Kensington','Payneham','Magill','Campbelltown SA','Newton','Dernancourt','Para Hills','Ingle Farm','Davoren Park','Smithfield SA','Angle Vale','Two Wells','Kapunda','Nuriootpa','Tanunda','Angaston','Clare','Kadina','Wallaroo','Moonta','Port Wakefield','Crystal Brook','Brighton SA','Seacliff','Somerton Park','Plympton','Richmond SA','Mile End','Thebarton','Hindmarsh','Croydon SA','Woodville','Findon','Fulham Gardens','Henley Beach','Grange','Semaphore','Largs Bay','North Haven','Osborne','Enfield','Klemzig','Windsor Gardens','Gilles Plains','Greenacres','Walkerville','Medindie','Glenside','Fullarton','Mitcham','Blackwood','Belair','Aberfoyle Park','Flagstaff Hill','Happy Valley','Reynella','Woodcroft','Seaford SA','Port Noarlunga','McLaren Vale','Willunga','Strathalbyn','Goolwa','Stirling SA','Aldgate','Hahndorf','Littlehampton','Nairne','Lobethal','Woodside SA','Berri','Renmark','Loxton','Waikerie','Naracoorte','Millicent','Bordertown','Ceduna','Port Lincoln','Roxby Downs','Peterborough SA'] },
  { label: 'Victoria', short: 'VIC', suburbs: ['Melbourne CBD','Richmond','Fitzroy','St Kilda','Prahran','South Yarra','Toorak','Hawthorn','Camberwell','Malvern','Caulfield','Carnegie','Oakleigh','Clayton','Dandenong','Frankston','Moorabbin','Bentleigh','Brighton VIC','Sandringham','Cheltenham VIC','Mentone','Mordialloc','Parkdale','Carrum','Seaford VIC','Geelong','Ballarat','Bendigo','Essendon','Footscray','Sunshine VIC','Werribee','Point Cook','Hoppers Crossing','Williamstown','Newport VIC','Altona','Laverton','Truganina','Melton','Bacchus Marsh','Keilor','Broadmeadows','Coburg','Preston','Northcote','Doncaster','Box Hill','Ringwood','Croydon VIC','Lilydale','Healesville','Mooroolbark','Bayswater','Wantirna','Knox','Rowville','Berwick','Narre Warren','Pakenham','Officer','Cranbourne','Brunswick','Carlton','Collingwood','Abbotsford VIC','Kew','Balwyn','Surrey Hills','Blackburn','Nunawading','Vermont','Glen Waverley','Mount Waverley','Burwood VIC','Ashburton VIC','Chadstone','Springvale','Noble Park','Keysborough','Mulgrave','Wheelers Hill','Endeavour Hills','Hallam','Hampton Park','Lynbrook','Clyde North','Mickleham','Craigieburn','Roxburgh Park','Epping VIC','Mill Park','South Morang','Mernda','Doreen','Whittlesea','Greensborough','Eltham','Diamond Creek','Hurstbridge','Reservoir','Thomastown','Lalor','Bundoora','Heidelberg','Ivanhoe','Sunbury','Gisborne','Kyneton','Woodend','Torquay VIC','Ocean Grove','Drysdale','Lara','Colac','Warrnambool','Portland VIC','Hamilton VIC','Horsham','Ararat','Stawell','Maryborough VIC','Castlemaine','Echuca','Shepparton','Wangaratta','Wodonga','Benalla','Seymour','Traralgon','Morwell','Moe','Warragul','Drouin','Leongatha','Wonthaggi','Sale VIC','Bairnsdale','Lakes Entrance','Mildura','Swan Hill'] },
  { label: 'New South Wales', short: 'NSW', suburbs: ['Sydney CBD','Parramatta','Bondi','Newtown','Manly','Chatswood','Hornsby','Penrith','Liverpool','Blacktown','Campbelltown NSW','Cronulla','Miranda','Sutherland','Hurstville','Kogarah','Rockdale','Bankstown','Lakemba','Strathfield','Burwood NSW','Auburn','Merrylands','Granville','Wentworthville','Seven Hills','Toongabbie','Mt Druitt','St Marys NSW','Kingswood','Katoomba','Richmond NSW','Windsor NSW','Rouse Hill','Castle Hill','Baulkham Hills','Kellyville','Norwest','Bella Vista','Newcastle','Maitland','Cessnock','Singleton','Muswellbrook','Wollongong','Dapto','Shellharbour','Kiama','Nowra','Albury','Wagga Wagga','Tamworth','Orange NSW','Dubbo','Broken Hill','Coffs Harbour','Port Macquarie','Armidale','Bathurst','Surry Hills','Paddington NSW','Bondi Junction','Randwick','Coogee','Maroubra','Kensington NSW','Mascot','Botany','Marrickville','Dulwich Hill','Ashfield','Leichhardt','Balmain','Drummoyne','Five Dock','Concord','Ryde','Epping NSW','Eastwood','Carlingford','Baulkham Hills North','Pennant Hills','Thornleigh','Wahroonga','Turramurra','Gordon NSW','Lindfield','North Sydney','Crows Nest','Mosman','Neutral Bay','Dee Why','Brookvale','Narrabeen','Mona Vale','Avalon','Fairfield NSW','Cabramatta','Canley Vale','Smithfield NSW','Wetherill Park','Prairiewood','Bonnyrigg','Green Valley','Casula','Ingleburn','Minto','Narellan','Camden NSW','Oran Park','Gregory Hills','Leppington','Austral','Marsden Park','Schofields','Riverstone','Quakers Hill','Glenwood','Stanhope Gardens','The Ponds','Box Hill NSW','Gosford','Erina','Terrigal','Wyong','Tuggerah','Toukley','The Entrance','Morisset','Charlestown','Belmont NSW','Raymond Terrace','Nelson Bay','Forster','Taree','Kempsey','Ballina','Lismore','Byron Bay','Tweed Heads NSW','Grafton','Goulburn','Queanbeyan','Griffith NSW','Parkes','Cowra','Mudgee','Lithgow','Bowral','Mittagong','Moss Vale','Ulladulla','Batemans Bay','Bega','Merimbula'] },
  { label: 'Queensland', short: 'QLD', suburbs: ['Brisbane CBD','Fortitude Valley','South Brisbane','West End QLD','Woolloongabba','Carindale','Mount Gravatt','Sunnybank','Moorooka','Rocklea','Acacia Ridge','Inala','Oxley','Darra','Richlands','Springfield QLD','Ipswich','Booval','Goodna','Redbank','Collingwood Park','Redbank Plains','Gold Coast','Surfers Paradise','Broadbeach','Southport','Robina','Burleigh Heads','Miami QLD','Palm Beach QLD','Coolangatta','Tweed Heads','Sunshine Coast','Maroochydore','Mooloolaba','Caloundra','Kawana Waters','Noosa','Toowoomba','Cairns','Townsville','Rockhampton','Bundaberg','Mackay','Hervey Bay','Gladstone','Mount Isa','Strathpine','Redcliffe','Deception Bay','Caboolture','Narangba','North Lakes','Mango Hill','Petrie','Brendale','New Farm','Newstead QLD','Bulimba','Hawthorne QLD','Morningside','Cannon Hill','Wynnum','Manly QLD','Capalaba','Cleveland QLD','Victoria Point','Redland Bay','Thornlands','Birkdale','Wellington Point','Springwood QLD','Underwood','Rochedale','Loganholme','Shailer Park','Beenleigh','Eagleby','Browns Plains','Regents Park QLD','Marsden','Crestmead','Kingston QLD','Woodridge','Slacks Creek','Chermside','Aspley','Bracken Ridge','Sandgate','Nundah','Clayfield','Ascot QLD','Hamilton QLD','Toowong','Indooroopilly','Kenmore','Chapel Hill','The Gap','Ferny Grove','Mitchelton','Everton Park','Stafford','Albany Creek','Eatons Hill','Warner','Cashmere','Samford','Dayboro','Woodford QLD','Kilcoy','Gympie','Maryborough QLD','Childers','Yeppoon','Emerald','Biloela','Warwick','Stanthorpe','Dalby','Chinchilla','Roma QLD','Kingaroy','Nambour','Coolum Beach','Peregian','Tewantin','Beerwah','Landsborough','Nerang','Mudgeeraba','Helensvale','Coomera','Ormeau','Pimpama','Jimboomba','Innisfail','Atherton','Mareeba','Port Douglas','Ayr','Bowen','Proserpine','Airlie Beach','Charters Towers'] },
  { label: 'Western Australia', short: 'WA', suburbs: ['Perth CBD','Fremantle','Joondalup','Rockingham','Mandurah','Bunbury','Geraldton','Albany','Kalgoorlie','Northbridge','Subiaco','Cottesloe','Claremont WA','Nedlands','Floreat','Wembley','Osborne Park','Stirling WA','Balcatta','Karrinyup','Duncraig','Hillarys','Currambine','Butler','Clarkson WA','Quinns Rocks','Alkimos','Yanchep','Midland','Swan View','Ellenbrook','Bullsbrook','Armadale','Kelmscott','Byford','Mundijong','Baldivis','Secret Harbour','Golden Bay','Waikiki','Safety Bay','Shoalwater','Singleton WA','Lakelands','Madora Bay','Port Kennedy','Canning Vale','Willetton','Booragoon','Applecross','Brentwood WA','Murdoch','Winthrop','Kardinya','Spearwood','Scarborough','Trigg','Sorrento WA','Marmion','Mullaloo','Ocean Reef','Beldon','Edgewater','Wanneroo','Landsdale','Madeley','Darch','Kingsley','Greenwood WA','Warwick WA','Innaloo','Doubleview','Mount Hawthorn','Leederville','Mount Lawley','Maylands WA','Bayswater WA','Morley','Dianella','Inglewood WA','Bassendean','Guildford WA','High Wycombe','Forrestfield','Kalamunda','Gosnells','Thornlie','Maddington','Huntingdale WA','Southern River','Harrisdale','Piara Waters','Atwell','Success','Cockburn Central','Bibra Lake','Hamilton Hill','Coogee WA','Munster','Wattleup','Kwinana','Medina','Calista','Busselton','Margaret River','Dunsborough','Collie','Manjimup','Katanning','Narrogin','Northam','York WA','Merredin','Esperance','Karratha','Port Hedland','Broome','Kununurra','Carnarvon','Exmouth','Newman','Tom Price'] },
  { label: 'Tasmania', short: 'TAS', suburbs: ['Hobart CBD','Sandy Bay','Battery Point','South Hobart','West Hobart','North Hobart','Glenorchy','Moonah','Claremont TAS','Rosny Park','Bellerive','Lindisfarne','Montrose','Launceston','Invermay','Newstead TAS','Kings Meadows','Newnham','Prospect TAS','Devonport','Spreyton','Ulverstone','Penguin','Burnie','Somerset','Wynyard','Smithton','Queenstown','Strahan','Huonville','Kingston TAS','Margate TAS','Snug','New Norfolk','Bridgewater','Brighton TAS','Howrah','Lauderdale','Sorell','Richmond TAS','Cambridge TAS','Old Beach','Granton','Berriedale','Chigwell','Austins Ferry','Lenah Valley','New Town TAS','Mowbray','Riverside TAS','Trevallyn','Youngtown','Legana','Perth TAS','Longford TAS','Deloraine','Westbury','George Town','Scottsdale','St Helens','Bicheno','Swansea TAS','Triabunna','Oatlands','Campbell Town','Ross TAS','Latrobe TAS','Port Sorell','Sheffield TAS','Railton','Currie','Cygnet','Geeveston','Dodges Ferry','Primrose Sands'] },
  { label: 'Australian Capital Territory', short: 'ACT', suburbs: ['Canberra CBD','Civic','Belconnen','Tuggeranong','Woden','Gungahlin','Weston Creek','Bruce ACT','Charnwood','Florey','Macquarie ACT','Page ACT','Scullin','Weetangera','Calwell','Greenway','Theodore','Kambah','Wanniassa','Erindale','Monash ACT','Fadden','Gowrie','Chisholm','Isabella Plains','Banks','Holt','Higgins','Spence','Latham','Macgregor ACT','Evatt','Giralang','Kaleen','Lyneham','OConnor ACT','Ainslie','Watson','Downer','Hackett','Dickson','Braddon','Turner ACT','Campbell ACT','Kingston ACT','Narrabundah','Griffith ACT','Red Hill ACT','Deakin','Yarralumla','Curtin ACT','Lyons ACT','Phillip ACT','Mawson ACT','Torrens','Pearce','Chifley ACT','Garran','Hughes','Farrer','Isaacs','Casey ACT','Crace','Franklin ACT','Harrison','Amaroo','Ngunnawal','Nicholls','Palmerston ACT','Forde','Bonner','Moncrieff','Throsby','Coombs','Wright ACT','Denman Prospect','Molonglo','Dunlop','Fraser ACT','Melba','Flynn ACT','Duffy','Holder','Rivett','Stirling ACT','Waramanga','Fisher ACT','Chapman','Bonython','Gordon ACT','Conder','Richardson','Oxley ACT','MacArthur','Symonston'] },
  { label: 'Northern Territory', short: 'NT', suburbs: ['Darwin CBD','Casuarina','Palmerston','Nightcliff','Rapid Creek','Fannie Bay','Stuart Park','Parap','Larrakeyah','Millner','Moil','Malak','Marrara','Berrimah','Humpty Doo','Coolalinga','Virginia NT','Batchelor','Pine Creek','Katherine','Tennant Creek','Alice Springs','Larapinta','Sadadeen','Gillen','Ross','Araluen','Wagaman','Wanguri','Leanyer','Karama','Anula','Jingili','Alawa','Brinkin','Tiwi NT','Lyons NT','Muirhead','Bakewell','Driver','Gray','Moulden','Woodroffe','Rosebery NT','Bellamack','Johnston','Zuccoli','Howard Springs','Girraween','Herbert','Noonamah','Adelaide River','Jabiru','Nhulunbuy','Yulara','Borroloola','Elliott'] },
]
